### ISSUE TITLE
"Missing class properties transform" exception when running npm test

### ISSUE THREAD

**Issue by lloydleo** [preactjs/jest-preset-preact#2]
Running `npm test` for a stateful component, after updating to latest versions (listed below), throws an exception. However the error disappears if downgrading jest-preset-preact to v1.0.0.

#### Repro steps

1. Install latest preact-cli.

1. Create a new preact app using default template.

`$ preact create default my-project`

1. Modify `src/components/header/index.js` to a stateful component:

```javascript

import { h, Component, render } from 'preact';
import { Link } from 'preact-router/match';
import style from './style.css';

export default class Header extends Component {
  state = {
    title: 'Preact App'
  };

  render(_, {title}) {
    return (
      <header class={style.header}>
        <h1>{title}</h1>
        <nav>
          <Link activeClassName={style.active} href="/">Home</Link>
          <Link activeClassName={style.active} href="/profile">Me</Link>
          <Link activeClassName={style.active} href="/profile/john">John</Link>
        </nav>
      </header>
    );
  }
}

```

1. Run `npm test` and it **works fine**.

1. Now Update lib versions to latest (only updated ones shown):

```json

  "devDependencies": {
    "enzyme": "^3.11.0",
    "enzyme-adapter-preact-pure": "^2.2.1",
    "jest": "^26.2.2",
    "jest-preset-preact": "^4.0.0",
  },
  "dependencies": {
    "preact": "^10.4.6",
  },

```

1. Running `npm test` results in an exception:

```bash

 FAIL  tests/header.test.js
 Test suite failed to run

    SyntaxError: pwa-test/src/components/header/index.js: Missing class properties transform.
      4 | 
      5 | export default class Header extends Component {
    > 6 |   state = {
        |   ^
      7 |     title: 'Preact App'
      8 |   };
      9 | 

      at File.buildCodeFrameError (node_modules/@babel/core/lib/transformation/file/file.js:248:12)
      at NodePath.buildCodeFrameError (node_modules/@babel/traverse/lib/path/index.js:144:21)
      at pushBody (node_modules/@babel/plugin-transform-classes/lib/transformClass.js:161:20)
      at buildBody (node_modules/@babel/plugin-transform-classes/lib/transformClass.js:135:5)
      at classTransformer (node_modules/@babel/plugin-transform-classes/lib/transformClass.js:544:5)
      at transformClass (node_modules/@babel/plugin-transform-classes/lib/transformClass.js:580:10)
      at PluginPass.ClassExpression (node_modules/@babel/plugin-transform-classes/lib/index.js:63:54)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:175:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.501 s

```

**Comment by marvinhagemeister** [comment]
@lloydleo Awesome, thank you so much for the bug report! I've published the fix with the just released version `4.0.1` 👍
